module.exports = {
0: ["33", "Calf", "EVO_FEMALE_LEVEL", "19", "Cow"],
1: ["33", "Calf", "EVO_MALE_LEVEL", "19", "Bull"],
2: ["33", "Calf", "EVO_ITEM", "ITEM_VANILLA_MILK", "Cow_Vanilla_Form"],
3: ["33", "Calf", "EVO_ITEM", "ITEM_STRAWBERRY_MILK", "Cow_Strawberry_Form"],
4: ["33", "Calf", "EVO_ITEM", "ITEM_CHOCOLATE_MILK", "Cow_Chocolate_Form"],
5: ["33", "Calf", "EVO_ITEM", "ITEM_CHAOS_RUNE", "Minotaur_Normal_Form"],
6: ["33", "Calf", "EVO_VAR", "7", "Cow_Undead_Form"],
7: ["33", "Calf", "EVO_OTHER_PARTY_MON", "Ram_Golden_Form", "Trojan_Cow"],
8: ["33", "Calf", "EVO_OTHER_PARTY_MON", "Unicorn_White_Form", "Unicow"],
9: ["34", "Cow", "EVO_FEMALE_DEATH", "30", "SkeletalOx_Female_Form"],
10: ["34", "Cow", "EVO_ITEM", "ITEM_DEATH_RUNE", "SkeletalOx_Female_Form"],
11: ["34", "Cow", "EVO_LEVEL_ATK_LT_DEF", "30", "Cow_Dairy_Form"],
12: ["34", "Cow", "EVO_LEVEL_ATK_GT_DEF", "30", "Super_Cow"],
}